### ISSUE TITLE
words ending in bym

### ISSUE THREAD

**Issue by dpinol** [Tutanchamon/pl_stemmer#2]
Hi
about https://github.com/Tutanchamon/pl_stemmer/blob/master/pl_stemmer.py#L187 I didn't find any word in Polish ending in "bym" (apart from acronyms). Is it a typo?

I checked
https://www.ezglot.com/words-ending-with.php?w=bym&l=pol&l2=&length=&submit=Search

**Comment by dzieciou** [comment]
It's suffix for conditional cases for first peson, singular:

- byłbym from być, english: I would be
- pojechałbym from pojechać, english: I would go

**Comment by dpinol** [comment]
thanks!
